### ISSUE TITLE
Curious about ReLU layers inside `resUnit`

### ISSUE THREAD

**Issue by gcr** [arunpatala/residual.mnist#8]
Hello!

I saw your MNIST writeup [here](http://yun.baidu.com/share/link?uk=2768594655&shareid=3354552551&third=0&adapt=pc&fr=ftw). Looks really cool!

I'm also trying to implement residual networks in torch with mixed success. It would be great to compare notes.

I'm curious: the call to `convunit()` always adds a ReLU layer to the end of each unit it constructs. This means that each `resUnit` is calculating `ReLU( ReLU(f(x)) + x )`. If I'm interpreting the architecture correctly, it looks like this:

![Example architecture](http://i.imgur.com/QZ1tg5K.png)

Doing this means that the first term of the sum can never be negative. What that means is that `x` will never decrease as it propagates through the network. I think this differs from the original paper: if I read correctly, they don't add that second ReLU until after the building block.

Would this affect performance at all?

(I'm not sure how much of an issue this is. [My experiments on CIFAR](https://github.com/gcr/torch-residual-networks#cifar-effect-of-model-architecture) are pretty inconclusive...)

**Comment by arunpatala** [comment]
Thanks for pointing this out. Yes the paper also suggested adding the on linearity after the addition operation. From my experiments, I did not see much difference, so I thought of keeping another layer of non linearity.  
Also great work on your cifar experiments. Looks pretty good. I also faced difficulties in replicating the results. Hope you have better luck.
